---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-system
spec:
  selector:
    matchLabels:
      app: auth-system
  template:
    metadata:
      labels:
        app: auth-system
    spec:
      containers:
      - name: auth-system
        image: trustartup.azurecr.io/authsystem
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: APP_ENV
            value: production
          - name: APP_KEY
            value: yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
          - name: APP_DEBUG
            value: "false"
          - name: API_USER
            value: http://user-system
          - name: PRIVATE_KEY
            value: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQBsAJJ+O3fTxnPlXCleUCLGleHad+0u/4P+qKoul2Sd49b6Ta/4
              OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBwVUDOG8E1VU8NDPN1/uSUz7+1yFO4
              DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGhVAZVhWdnJmRFcvBB98HoA2/x5Lkv
              78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi6kzPyVHI36mK0PcManhMBWQOupj1
              p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5PbjrUycVRhYZFM6wDYEMdooQR46Ie/
              tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2tAgMBAAECggEACjRDowmbWLb3XERI
              5FBN+NVQcYPDNR2PKxBkg+Jp70EHnr6YUaun88jJIdQ0Epj1H+NzEyTmpKnOmo9l
              TB30RajIZrDYoGFfBqyilBNxJV47jsFOp6U4tYaqOF37TOWW5x2y7ROuJGUTIjMy
              YRchQEzgDFR+YJCQCL/DU3hFKdaJ1UPko5IearZJmFHAik1KaXETXqj62+6qvlp0
              n1mat72Pa8N3xNwK/36v2oqJBy7hFPz/QlCAe6+Lx86Ujsf9mXWHWbCLyLOAJ3a+
              PcicbVhL5mVmMnL6VK5xqyO6mjYD76u1IcorRveq5a5Uc5wWkh4mskflbePcEvtM
              /OcJQQKBgQCvqsPtua00Kyu5npBI+aqPWlALP1f33qMQQUIzT8krc3ihxr6Rv6Yj
              MLsFSqZxPMjgqVkaR5xaF8fCtWu0+CqJ0i9046r4UW2xn0PJ+2+ttTbpiuQ7LIR5
              eZ1XPYhkcqDWhgY3VFuUXNe6MlBZmoNH5mDbqvinfzPRoI8qViFOswKBgQCdZFP7
              cVmnkxuyzmaN+BNaRNyXrUHjFIfHeWLd3urvspMbxCBu/Sj+RIRxC2yP6zBDu3SA
              sVwo59Iko6DP2ZuCIOoek6fh1qKMVrhvEXYU3rSvQ5x0KzksrTwzde1bxQY1ptOQ
              BtRKjR8saCOD3BRxXbwqzxbWAvF6Ha8ahzQSHwKBgQCuqMIf9lJBIX9bEk3xUNOF
              rs0RMcz8NY+51LjGndit7CSP7TSDY6MDMCtzKnLs+fvcbGScXYEWjrheXtWVXH2n
              BKWMueS++u9vAKR9ChNTCm9rq14be7rHsOSA3jxjaxmB0kYR8z0O+XTAu8/qF1fa
              QDQjlQ2gNDhIgDR4aqS5QwKBgGfZ6lwv17NtqsoZzKuCc+qNI2zlgmL+ifUB0E2L
              qENO9ihNCgWR/7l+plEc854m1mrqxp2f6aqIBC3u1c4vzJ9ZboGMdira/9hP5FRN
              FjgBFwHKP/KbDpe/Gsjt2BdEcqt2D4SqLOugIGChukVoMwj2i5FHoc7GlGU6Lu73
              JVGLAoGBAIHbIhy4W13R4m4suFgBc08O1Jgt0lLQWaQstnvESrr/6roBSo9p46n9
              rIfWWVD94phQVQz7sTAPD8HIGjsn3f2uZR/23O9/rOqdG5rj5y9TwZg3zAlVGB8E
              GLH1GOGjMdgyosxMyajWTxyJVhsRcdRl1fIoI0mGteK9V8NXJTLZ
              -----END RSA PRIVATE KEY-----
          - name: PUBLIC_KEY
            value: |
              -----BEGIN PUBLIC KEY-----
              MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLG
              leHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBw
              VUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGh
              VAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi
              6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5Pb
              jrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2t
              AgMBAAE=
              -----END PUBLIC KEY-----
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: auth-system
spec:
  selector:
    app: auth-system
  ports:
  - port: 80
    targetPort: 80
