---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-content
spec:
  selector:
    matchLabels:
      app: business-content
  template:
    metadata:
      labels:
        app: business-content
    spec:
      containers:
      - name: business-content
        image: trustartup.azurecr.io/businesscontent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/sh", "-c"]
        args: ["php artisan migrate --force && /docker-entrypoint.sh"]
        env:
          - name: APP_ENV
            value: production
          - name: APP_KEY
            value: yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
          - name: APP_DEBUG
            value: "false"
          - name: DB_CONNECTION
            value: pgsql
          - name: DB_HOST
            value: business-content-db
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: postgres
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: postgres
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: business-content
spec:
  selector:
    app: business-content
  ports:
  - port: 80
    targetPort: 80
