---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-logic
spec:
  selector:
    matchLabels:
      app: feed-logic
  template:
    metadata:
      labels:
        app: feed-logic
    spec:
      containers:
      - name: feed-logic
        image: trustartup.azurecr.io/feedlogic
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Authentication__JwtRsaPublicKey
          value: MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLGleHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBwVUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGhVAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5PbjrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2tAgMBAAE=
        - name: Settings__FeedContentSystemUrl
          value: http://feed-content
        - name: Settings__MediaSystemUrl
          value: http://media-system
        - name: Settings__UserSystemUrl
          value: http://user-system
        - name: Settings__PaymentSystemUrl
          value: http://payment-system
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: feed-logic
spec:
  selector:
    app: feed-logic
  ports:
  - port: 80
    targetPort: 80

