---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-response
spec:
  selector:
    matchLabels:
      app: media-response
  template:
    metadata:
      labels:
        app: media-response
    spec:
      containers:
      - name: media-response
        image: trustartup.azurecr.io/mediaresponse
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Authentication__JwtRsaPublicKey
          value: MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBsAJJ+O3fTxnPlXCleUCLGleHad+0u/4P+qKoul2Sd49b6Ta/4OfK/NCGDhzCSEYSqXBIiEPEuUtKJgk8xvzBwVUDOG8E1VU8NDPN1/uSUz7+1yFO4DpFQA/VgQaPXBhxO6JnpyDyHvX/4UuBs4QGhVAZVhWdnJmRFcvBB98HoA2/x5Lkv78nAdT65gXWKdVe1eo+61nH5g8JwHEKJ6sPi6kzPyVHI36mK0PcManhMBWQOupj1p0NWQjuphMLkJyMpeN2FiqT1GTUnOKe1M5PbjrUycVRhYZFM6wDYEMdooQR46Ie/tLXyr4k47qlI+LkxIAkkAerlF9D8uqEm7R2tAgMBAAE=
        - name: Settings__MediaSystemUrl
          value: http://media-system
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: media-response
spec:
  selector:
    app: media-response
  ports:
  - port: 80
    targetPort: 80

