---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-system
spec:
  selector:
    matchLabels:
      app: user-system
  template:
    metadata:
      labels:
        app: user-system
    spec:
      containers:
      - name: user-system
        image: trustartup.azurecr.io/usersystem
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/sh", "-c"]
        args: ["php artisan migrate --force --seed && /docker-entrypoint.sh"]
        env:
          - name: APP_ENV
            value: production
          - name: APP_KEY
            value: yIcTghI5UqQY6z3IjTCupEbHMYPH73gJ
          - name: APP_DEBUG
            value: "false"
          - name: DB_CONNECTION
            value: pgsql
          - name: DB_HOST
            value: user-system-db
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: postgres
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: postgres
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-system
spec:
  selector:
    app: user-system
  ports:
  - port: 80
    targetPort: 80
