---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-content-db
spec:
  selector:
    matchLabels:
      app: business-content-db
  template:
    metadata:
      labels:
        app: business-content-db
    spec:
      containers:
      - name: business-content-db
        image: postgres:14.1-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: business-content-db-secret
                key: dbPassword
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pg-data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: business-content-db-volume

---
apiVersion: v1
kind: Service
metadata:
  name: business-content-db
spec:
  selector:
    app: business-content-db
  ports:
  - port: 5432
    targetPort: 5432

