---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-system
spec:
  selector:
    matchLabels:
      app: media-system
  template:
    metadata:
      labels:
        app: media-system
    spec:
      containers:
      - name: media-system
        image: trustartup.azurecr.io/mediasystem:157
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: media-system-secret
              key: dbConnectionString
        - name: Storage__Path
          value: /app/media/
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /app/media
            name: media-data
      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: media-system-volume
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: media-system
spec:
  selector:
    app: media-system
  ports:
  - port: 80
    targetPort: 80

