apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-system-db-volume
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default
